import { PLACE_ARCHETYPE_OPTIONS } from '../../utils/placePresets';

export const PLACE_SELECTION_OPTIONS = [
  ...PLACE_ARCHETYPE_OPTIONS,
  { id: 'none', label: 'どれにも当てはまらない' },
];

export const AR_POSTING_COPY = {
  chooseTitle: '記録のしかたを選ぶ',
  chooseDescription: '現地で撮影するか、地図で場所を指定して訪問時の写真を添付してください',
  onsiteTitle: '現地で撮影',
  onsiteHint: 'その場でカメラを使う（高報酬）',
  mapTitle: '地図で場所を指定',
  mapHint: 'ピン＋訪問時に撮った写真（補助チャネル）',
  mapPhotoTitle: '訪問時の写真を選ぶ',
  mapPhotoDescription: '地図で指定した場所を訪れたときに撮影した写真を添付してください（必須）',
  pickPhoto: '写真を選ぶ',
  modeMap: '地図投稿',
  modeOnsite: '現地投稿',
  scanPrompt: '街の記録をスキャン',
  stepHeader: '撮影完了：評価を選んで記録',
  annotationTitle: '空間注釈をつける',
  annotationHint: '気になる場所をタップしてピン（最大5個・任意）',
  annotationEditHint: '写真の気になる場所をタップしてピンを追加・削除できます',
  annotationNext: '次へ',
  goodSubmit: 'Good Spot 図鑑に登録',
  badSubmit: 'クエストボードに登録する',
};

export const AR_POSTING_STYLE = {
  choiceCardBase: {
    borderRadius: '22px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: 'all 0.2s',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    textAlign: 'center',
    padding: '22px 16px',
  },
  roundCloseButton: {
    position: 'absolute',
    top: '30px',
    left: '30px',
    zIndex: 7,
    pointerEvents: 'auto',
    background: 'rgba(0,0,0,0.5)',
    border: 'none',
    borderRadius: '50%',
    padding: '10px',
    cursor: 'pointer',
    color: 'white',
  },
  modeBadgeBase: {
    position: 'absolute',
    top: '30px',
    right: '24px',
    zIndex: 7,
    pointerEvents: 'auto',
    background: 'rgba(0,0,0,0.55)',
    padding: '8px 14px',
    borderRadius: 16,
    fontWeight: 'bold',
    fontSize: 14,
  },
  sheetDecision: {
    background: 'rgba(255,255,255,0.96)',
    padding: '24px 24px',
    borderTopLeftRadius: '30px',
    borderTopRightRadius: '30px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    boxShadow: '0 -12px 24px rgba(0,0,0,0.22)',
    minHeight: '34vh',
    maxHeight: '46vh',
    overflowY: 'auto',
  },
  annotationFooter: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 8,
    pointerEvents: 'none',
    padding: '0 16px max(16px, env(safe-area-inset-bottom))',
    background: 'linear-gradient(to top, rgba(0,0,0,0.82) 0%, rgba(0,0,0,0.45) 55%, transparent 100%)',
  },
  annotationFooterInner: {
    pointerEvents: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    paddingTop: '40px',
    paddingBottom: '8px',
  },
  annotationHintText: {
    flex: 1,
    margin: 0,
    color: '#f5f5f5',
    fontSize: '13px',
    lineHeight: 1.4,
    fontWeight: 600,
  },
  annotationStepBadge: {
    position: 'absolute',
    top: '30px',
    right: '24px',
    zIndex: 8,
    pointerEvents: 'none',
    background: 'rgba(0,0,0,0.55)',
    color: '#fff',
    padding: '8px 14px',
    borderRadius: 16,
    fontWeight: 'bold',
    fontSize: 14,
  },
  annotationNavButton: {
    borderRadius: '14px',
    fontWeight: 'bold',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '12px 18px',
    minWidth: '88px',
    border: 'none',
  },
  sheetDetail: {
    background: 'rgba(255,255,255,0.97)',
    padding: '28px 24px 32px',
    borderTopLeftRadius: '34px',
    borderTopRightRadius: '34px',
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    boxShadow: '0 -16px 34px rgba(0,0,0,0.3)',
    minHeight: '88vh',
    maxHeight: '98vh',
    overflowY: 'auto',
  },
};

export const getModeBadgeStyle = (captureMode) => ({
  ...AR_POSTING_STYLE.modeBadgeBase,
  color: captureMode === 'map' ? '#81d4fa' : 'white',
});

export const getSheetStyle = (isDecisionStep) => (
  isDecisionStep ? AR_POSTING_STYLE.sheetDecision : AR_POSTING_STYLE.sheetDetail
);
