export const GOOD_SPOT_BOOK_COPY = {
  title: 'Good Spot 図鑑',
  close: '閉じる',
  empty: 'まだ Good Spot はありません。AR投稿で「Good」を選んで登録できます。',
  noPhoto: 'No Photo',
  defaultTagLabel: '#みんなに優しい場所',
  noComment: '（コメントなし）',
  unknownDemographic: '投稿者不明',
};

export const GOOD_SPOT_BOOK_STYLE = {
  backdrop: {
    position: 'absolute',
    inset: 0,
    background: 'rgba(0,0,0,0.62)',
    backdropFilter: 'blur(8px)',
    zIndex: 260,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  panel: {
    width: '92%',
    maxWidth: '860px',
    maxHeight: '84vh',
    background: 'rgba(8,12,20,0.95)',
    border: '1px solid rgba(129,212,250,0.4)',
    borderRadius: '18px',
    overflow: 'hidden',
    boxShadow: '0 18px 44px rgba(0,0,0,0.45)',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px',
    borderBottom: '1px solid rgba(255,255,255,0.1)',
  },
  title: {
    color: '#d7f3ff',
    fontWeight: 'bold',
    fontSize: '18px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  closeButton: {
    background: 'rgba(255,255,255,0.08)',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.25)',
    borderRadius: '999px',
    padding: '6px 12px',
    cursor: 'pointer',
    fontWeight: 'bold',
  },
  grid: {
    padding: '16px',
    maxHeight: '72vh',
    overflowY: 'auto',
    display: 'grid',
    gap: '12px',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
  },
  empty: {
    gridColumn: '1 / -1',
    color: '#90a4ae',
    textAlign: 'center',
    padding: '26px 0',
  },
  card: {
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  photo: {
    height: '118px',
    background: '#102027',
    position: 'relative',
  },
  photoImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  noPhoto: {
    width: '100%',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#90a4ae',
    fontSize: '12px',
  },
  body: {
    padding: '10px',
  },
  tagLabel: {
    fontSize: '11px',
    color: '#80deea',
    fontWeight: 'bold',
  },
  comment: {
    marginTop: '4px',
    color: '#e1f5fe',
    fontSize: '12px',
    lineHeight: 1.4,
  },
  demographic: {
    marginTop: '6px',
    color: '#90a4ae',
    fontSize: '11px',
  },
};
